site_name: MkDocs Aide en ligne Projet
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Bienvenue: 'Bienvenue.md'
  - API : 'api.md'
  - Usage : 'usage.md'