site_name: Aide en ligne
#logo: "docs/favicon.png" 
theme:
  name: readthedocs
  highlightjs: true
  #navigation_depth: 6
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Bienvenue: 'index.md'
  - Conditions de licence des progiciels GESTIMUM et d'utilisation des services associés au 15/11/2019: 'CLS.md'
  - Notes de Version:
    - Bienvenue: 'NotesVersion/Racine/Bienvenue.md'
    - Mise en Garde: 'NotesVersion/Racine/MiseGarde.md'
    - Dénomination des versions: 'NotesVersion/Racine/DenominationVersion.md'
    - Développement sur mesure: 'NotesVersion/Racine/PFD.md'
    - Préconisations d'utilisation et d'installation: 'NotesVersion/Racine/PreconisationsUtilisationInstallation8.md'
  - Société:
    - Menu Société: 'Societe/Menu/Menu_SOCIETE.md'
    - Nouvelle société: 
      - Créer une nouvelle société: Societe/Nouvelle/1
        - Nouvelle société: 'Societe/Nouvelle/1/NouvelleSociete.md'
        - Base de données: 'Societe/Nouvelle/1/BaseDonnees.md'
        - Raison sociale et adresse: 'Societe/Nouvelle/1/RaisonSocialeAdresse.md'
        - Exercices comptables: 'Societe/Nouvelle/1/ExercicesComptables.md'
        - Tableau des périodes d'exercices comptables: 'Societe/Nouvelle/1/TableauPeriodes.md'
        - Données par défaut: 'Societe/Nouvelle/1/DonneesDefaut.md'
      - Dupliquer une société: 'Societe/Nouvelle/2/DupliquerBaseDonnees.md'
      - Paramétrages après la création d'une société: 'Societe/Nouvelle/3/ParametragesApresCreationSociete.md'