site_name: MkDocs Aide en ligne Projet
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Bienvenue: 'index.md'
  - Conditions de licence des progiciels GESTIMUM et d'utilisation des services associés au 15/11/2019: 'CLS.md'
  - Notes de Version:
    - Bienvenue: 'NotesVersion/Racine/Bienvenue.md'
    - Mise en Garde: 'NotesVersion/Racine/MiseGarde.md'
    - Dénomination des versions: 'NotesVersion/Racine/DenominationVersion.md'
    - Développement sur mesure: 'NotesVersion/Racine/PFD.md'
    - Préconisations d'utilisation et d'installation: 'NotesVersion/Racine/PreconisationsUtilisationInstallation8.md'