site_name: Aide en ligne
#logo: "docs/favicon.png" 
theme:
  name: readthedocs
  highlightjs: true
  navigation_depth: 1
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
plugins:
  - search
  - literate-nav:
    nav_file: SOMMAIRE.yml
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition