site_name: Aide en ligne
#logo: "docs/favicon.png" 
theme:
  name: readthedocs
  highlightjs: true
  features:
    - navigation.indexes
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Bienvenue: 'index.md'
  - Conditions de licence des progiciels GESTIMUM et d'utilisation des services associés au 15/11/2019: 'CLS.md'
  - Notes de Version:
    - Bienvenue: 'NotesVersion/Racine/Bienvenue.md'
    - Mise en Garde: 'NotesVersion/Racine/MiseGarde.md'
    - Dénomination des versions: 'NotesVersion/Racine/DenominationVersion.md'
    - Développement sur mesure: 'NotesVersion/Racine/PFD.md'
    - Préconisations d'utilisation et d'installation: 'NotesVersion/Racine/PreconisationsUtilisationInstallation8.md'
  - Société:
    - Menu Société: 'Societe/Menu/Menu_SOCIETE.md'
    - Nouvelle société: 
      - Créer une nouvelle société: 
        - 'Societe/Nouvelle/1/CreerNouvelleSociete.md'
        - Nouvelle société: 'Societe/Nouvelle/1/NouvelleSociete.md'
        - Base de données: 'Societe/Nouvelle/1/BaseDonnees.md'
        - Raison sociale et adresse: 'Societe/Nouvelle/1/RaisonSocialeAdresse.md'
        - Exercices comptables: 'Societe/Nouvelle/1/ExercicesComptables.md'
        - Tableau des périodes d'exercices comptables: 'Societe/Nouvelle/1/TableauPeriodes.md'
        - Données par défaut: 'Societe/Nouvelle/1/DonneesDefaut.md'
      - Dupliquer une société: 'Societe/Nouvelle/2/DupliquerBaseDonnees.md'
      - Paramétrages après la création d'une société: 'Societe/Nouvelle/3/ParametragesApresCreationSociete.md'
    - Ouvrir une société:
      - Ouverture de société: 'Societe/Ouvrir/1/OuvertureSociete.md'
      - Assistant de création d'une connexion à une société existante:
        - Assistant de connexion: 
          - 'Societe/Ouvrir/2/AssistantConnexion.md'
          - Base de données: 'Societe/Ouvrir/2/BaseDonnees.md'
          - Utilisateur et options: 'Societe/Ouvrir/2/UtilisateurOptions.md'
    - Fermer la société: 'Societe/Fermer/FermerSociete.md'
    - Paramétrage:
      - Préférences de société:
        - 'Societe/PreferencesSociete/1/PreferencesSociete.md'
        - Coordonnées: 'Societe/PreferencesSociete/2-1/OngletCoordonnees.md'
        - Logo: 'Societe/PreferencesSociete/2-1/OngletLogo.md'
        - Identité: 'Societe/PreferencesSociete/2-2/OngletIdentite.md'
        - Exercices: 'Societe/PreferencesSociete/2-3/OngletExercices.md'
        - Comptabilité: 'Societe/PreferencesSociete/2-4/OngletComptabilite.md'
        - Transfert comptable: 'Societe/PreferencesSociete/2-4/OngletTransfertComptable.md'
        - Racines: 
          - 'Societe/PreferencesSociete/2-5/OngletRacines.md'
          - Immobilisations: 'Societe/PreferencesSociete/2-5/OngletRacinesImmoibilisations.md'
          - Stocks: 'Societe/PreferencesSociete/2-5/OngletRacinesStocks.md'
          - Tiers: 'Societe/PreferencesSociete/2-5/OngletRacinesTiers.md'
          - Taxes: 'Societe/PreferencesSociete/2-5/OngletRacinesTaxes.md'
          - Finances: 'Societe/PreferencesSociete/2-5/OngletRacinesFinances.md'
          - Charges et Produits: 'Societe/PreferencesSociete/2-5/OngletRacinesChargesProduits.md'
          - Autres: 'Societe/PreferencesSociete/2-5/OngletRacinesAutres.md'
        - Comptes: 'Societe/PreferencesSociete/2-6/OngletComptes.md'
        - Encaissements: 'Societe/PreferencesSociete/2-7/OngletEncaissements.md'
        - Compteurs: 
          - 'Societe/PreferencesSociete/2-8/OngletCompteurs.md'
          - Pièces de vente: 'Societe/PreferencesSociete/2-8/OngletCompteursVentes.md'
          - Pièces d'achat: 'Societe/PreferencesSociete/2-8/OngletCompteursAchats.md'
          - Pièces de stock: 'Societe/PreferencesSociete/2-8/OngletCompteursStocks.md'
          - Pièces de trésorerie: 'Societe/PreferencesSociete/2-8/OngletCompteursTresorerie.md'
          - Numéros internes: 'Societe/PreferencesSociete/2-8/OngletCompteursNumeriques.md'
        - Styles: 'Societe/PreferencesSociete/2-9/OngletStyles.md'
        - Avancé: 'Societe/PreferencesSociete/2-9/OngletAvance.md'
        - Impression des préférences de la société: 'Societe/PreferencesSociete/3/Impression.md'
        - Lettrage automatique lors du transfert comptable: 'Societe/PreferencesSociete/Trier/LettrageAutomatiqueTransfertComptable.md'
        - Mode Fiche: 'Societe/PreferencesSociete/Trier/ModeFiche.md'
      - Préférences de gestion :
        - 'Societe/PreferencesGestion/1/PreferencesGestion.md'
        - Articles: 
          - Articles: 'Societe/PreferencesGestion/2-1/OngletArticles.md'
          - Critères personnalisés: 'Societe/PreferencesGestion/2-1/OngletCriteresPersonnalises.md'
          - Taxes parafiscales: 'Societe/PreferencesGestion/2-1/OngletTaxesParafiscales.md'
        - Stocks:
          - 'Societe/PreferencesGestion/2-2/OngletStocks.md'
          - Numéros de lots: 'Societe/PreferencesGestion/2-2/OngletNumerosLots.md'
          - Numéros de séries:  'Societe/PreferencesGestion/2-2/OngletNumerosSeries.md'
        - Tiers:
          - 'Societe/PreferencesGestion/2-3/OngletTiers.md'
          - Critères personnalisés: 'Societe/PreferencesGestion/2-3/OngletCriteresPersonnalises.md'
        - Ventes, achats, stocks:
          - 'Societe/PreferencesGestion/2-4/OngletVentesAchatsStocks.md'
          - Ventes: 'Societe/PreferencesGestion/2-4/OngletVentesAchatsVentes1.md'
          - Achats:  'Societe/PreferencesGestion/2-4/OngletVentesAchatsAchats.md'
          - Noms des documents:
            - 'Societe/PreferencesGestion/2-4/Noms/OngletNomsDocuments.md'
            - Ventes: 'Societe/PreferencesGestion/2-4/Noms/OngletNomsVentes.md'
            - Achats: 'Societe/PreferencesGestion/2-4/Noms/OngletNomsAchats.md'
            - Stocks: 'Societe/PreferencesGestion/2-4/Noms/OngletNomsStocks.md'
          - Modèles par défaut:
            - 'Societe/PreferencesGestion/2-4/Modeles/OngletVentesAchatsStocksModelesDefaut.md'
            - Ventes: 'Societe/PreferencesGestion/2-4/Modeles/OngletModelesVentes.md'
            - Achats: 'Societe/PreferencesGestion/2-4/Modeles/OngletModelesAchats.md'
            - Stocks: 'Societe/PreferencesGestion/2-4/Modeles/OngletModelesStocks.md'
          - Mentions obligatoires: 'Societe/PreferencesGestion/2-4/OngletMentionsObligatoires.md'
        - Affaires:
          - 'Societe/PreferencesGestion/2-5/OngletAffaires.md'
          - Ajouter les jours fériés: 'Societe/PreferencesGestion/2-5/AjouterJoursFeries.md'
        - Salariés: 
          - Critères personnalisés: 'Societe/PreferencesGestion/2-6/CriteresPersonnalises.md'
        - Impression des préférences de gestion: 'Societe/PreferencesGestion/3/Impression.md'
        - Messages d'avertissement ou bloquant: 'Societe/PreferencesGestion/Trier/MessagesAvertissementBloquant.md'
        - Date de livraison: 'Societe/PreferencesGestion/Trier/DateLivraison.md'
      - Préférences de comptabilité:
        - 'Societe/PreferencesCompta/1/PreferencesComptabilite.md'
        - Comptabilité: 'Societe/PreferencesCompta/2-1/OngletComptabilite.md'
        - Déclarations de TVA: 'Societe/PreferencesCompta/2-2/OngletDeclarationsTVA.md'
        - Fiscalité - FEC: 'Societe/PreferencesCompta/2-3/OngletFiscalite.md'
        - Trésor Public: 'Societe/PreferencesCompta/2-4/OngletTresorPublic.md'
        - Rapprochements bancaires: 'Societe/PreferencesCompta/2-5/OngletRapprochementsBancaires.md'
        - Immobilisations: 'Societe/PreferencesCompta/2-6/OngletImmobilisations.md'
        - Impression des préférences de comptabilité: 'Societe/PreferencesCompta/3/ImpressionPreferencesComptabilite.md'
      - Préférences utilisateur:
        - 'Societe/PreferencesUtilisateur/1/PreferencesUtilisateur.md'
        - Dossiers: 'Societe/PreferencesUtilisateur/2-1/OngletDossiers.md'
        - Imports d'achats, ventes et stocks: 'Societe/PreferencesUtilisateur/2-2/OngletImportAchatsVentesStocks.md'
        - Exports d'achats, ventes et stocks: 'Societe/PreferencesUtilisateur/2-3/OngletExportsAchatsVentesStocks.md'
        - Options: 'Societe/PreferencesUtilisateur/2-4/OngletOptions.md'
        - Documentation: 'Societe/PreferencesUtilisateur/2-5/OngletDocumentation.md'
        - Fichiers de configuartion: 'Societe/PreferencesUtilisateur/2-6/OngletFichiersConfiguration.md'
        - base de données: 'Societe/PreferencesUtilisateur/2-7/OngletBaseDonnees.md'
      - Tables de références:
        - Présentation: 'Societe/TablesReferences/1/Presentation.md'
        - Liste des tables de référence: 
          - Liste des tables de référence: 'Societe/TablesReferences/2/Liste.md'
          - Tables générales: 'Societe/TablesReferences/2/TablesReferenceGenerales.md'
          - Tables pour les affaires: 'Societe/TablesReferences/2/Affaires.md'
          - Tables pour les articles: 'Societe/TablesReferences/2/Articles.md'
          - Tables pour la comptabilité: 'Societe/TablesReferences/2/Comptabilite.md'
          - Tables pour les contacts: 'Societe/TablesReferences/2/Contacts.md'
          - Tables pour les documents d'achat, vente et stock: 'Societe/TablesReferences/2/DocumentsAchatVenteStock.md'
          - Tables pour les encaissements et décaissements: 'Societe/TablesReferences/2/TablesReferenceEncaissementsDecaissements.md'
          - Tables pour la prospection: 'Societe/TablesReferences/2/Prospection.md'
          - Tables pour les salariés: 'Societe/TablesReferences/2/TablesSalaries.md'
          - Tables pour le stock: 'Societe/TablesReferences/2/TablesStock.md'
          - Tables pour les tiers: 'Societe/TablesReferences/2/TablesTiers.md'
        - Saisie de valeurs dans les tables de référence: 'Societe/TablesReferences/3/SaisieValeurs.md'
        - Impression des tables de référence: 'Societe/TablesReferences/4/Impression.md'
      - Champs personnalisables:
        - Introduction: 'Societe/ChampsPersonnalises/0/Introduction.md'
        - Paramétrage: 
          - Création d'un champ personnalisé: 'Societe/ChampsPersonnalises/1/CreationChampPersonnalise.md'
          - Résultat dans les fenêtres concernées: 'Societe/ChampsPersonnalises/ResultatFenêrtesConcernees.md'
          - Valeurs possibles d'une liste déroulante: 'Societe/ChampsPersonnalises/2/ValeursPossiblesListeDeroulante.md'
          - Liste déroulante avec les valeurs d'une table: 'Societe/ChampsPersonnalises/3/ListeDeroulanteTableLiee.md'
          - Champs personnalisés calculés: 'Societe/ChampsPersonnalises/4/ChampsPersonnalisesCalcules.md'
          - Compteurs: 'Societe/ChampsPersonnalises/4/Compteurs.md'
          - Champs personnalisés obligatoires: 'Societe/ChampsPersonnalises/5/ChampsPersonnalisesObligatoires.md'
          - Conditions de visibilité: 'Societe/ChampsPersonnalises/6/ConditionsVisibilite.md'
        - Champs personnalisés dans les personnalisations de listes: 'Societe/ChampsPersonnalises/7/PersonnalisationsListes.md'
        - Recopie automatique de champs personnalisés entre tables: 'Societe/ChampsPersonnalises/8/RecopieAutomatiqueEntreTables.md'
      - Débrider mon ERP : 'Societe/Debridage/DebriderMonERP.md'
    - Services:
      - Liste des services: 'Societe/Services/1/Liste.md'
      - Service:
        - 'Societe/Services/2/Service.md'
        - Général: 'Societe/Services/2/OngletGeneral.md'
        - Divisions: 'Societe/Services/2/OngletDivisions.md'
      - Impression des services: 'Societe/Services/3/Impression.md'