site_name: Aide en ligne
#logo: "docs/favicon.png" 
theme:
  name: readthedocs
  highlightjs: true
  navigation_depth: 6
  features:
    - navigation.sections
    - navigation.indexes
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
nav:
  - Bienvenue: 'index.md'
  - Conditions de licence des progiciels GESTIMUM et d'utilisation des services associés au 15/11/2019: 'CLS.md'
  - Notes de Version:
    - Bienvenue: 'NotesVersion/Racine/Bienvenue.md'
    - Mise en Garde: 'NotesVersion/Racine/MiseGarde.md'
    - Dénomination des versions: 'NotesVersion/Racine/DenominationVersion.md'
    - Développement sur mesure: 'NotesVersion/Racine/PFD.md'
    - Préconisations d'utilisation et d'installation: 'NotesVersion/Racine/PreconisationsUtilisationInstallation8.md'
  - Société:
    - Menu Société: 'Societe/Menu/Menu_SOCIETE.md'
    - Nouvelle société: 
      - Créer une nouvelle société: 
        - Societe/Nouvelle/1/CreerNouvelleSociete.md
        - Nouvelle société: 'Societe/Nouvelle/1/NouvelleSociete.md'
        - Base de données: 'Societe/Nouvelle/1/BaseDonnees.md'
        - Raison sociale et adresse: 'Societe/Nouvelle/1/RaisonSocialeAdresse.md'
        - Exercices comptables: 'Societe/Nouvelle/1/ExercicesComptables.md'
        - Tableau des périodes d'exercices comptables: 'Societe/Nouvelle/1/TableauPeriodes.md'
        - Données par défaut: 'Societe/Nouvelle/1/DonneesDefaut.md'
      - Dupliquer une société: 'Societe/Nouvelle/2/DupliquerBaseDonnees.md'
      - Paramétrages après la création d'une société: 'Societe/Nouvelle/3/ParametragesApresCreationSociete.md'
    - Ouvrir une société:
      - Ouverture de société: 'Societe/Ouvrir/1/OuvertureSociete.md'
      - Assistant de création d'une connexion à une société existante:
        - Assistant de connexion: 
          - 'Societe/Ouvrir/2/AssistantConnexion.md'
          - Base de données: 'Societe/Ouvrir/2/BaseDonnees.md'
          - Utilisateur et options: 'Societe/Ouvrir/2/UtilisateurOptions.md'
    - Fermer la société: 'Societe/Fermer/FermerSociete.md'
    - Paramétrage:
      - Préférences de société:
        - 'Societe/PreferencesSociete/1/PreferencesSociete.md'
        - Coordonnées: 'Societe/PreferencesSociete/2-1/OngletCoordonnees.md'
        - Logo: 'Societe/PreferencesSociete/2-1/OngletLogo.md'
        - Identité: 'Societe/PreferencesSociete/2-2/OngletIdentite.md'
        - Exercices: 'Societe/PreferencesSociete/2-3/OngletExercices.md'
        - Comptabilité: 'Societe/PreferencesSociete/2-4/OngletComptabilite.md'
        - Transfert comptable: 'Societe/PreferencesSociete/2-4/OngletTransfertComptable.md'
        - Racines: 'Societe/PreferencesSociete/2-5/OngletRacines.md'
        - Immobilisations: 'Societe/PreferencesSociete/2-5/OngletRacinesImmoibilisations.md'
        - Stocks: 'Societe/PreferencesSociete/2-5/OngletRacinesStocks.md'
        - Tiers: 'Societe/PreferencesSociete/2-5/OngletRacinesTiers.md'
        - Taxes: 'Societe/PreferencesSociete/2-5/OngletRacinesTaxes.md'
        - Finances: 'Societe/PreferencesSociete/2-5/ngletRacinesFinances.md'
        - Charges et Produits: 'Societe/PreferencesSociete/2-5/OngletRacinesChargesProduits.md'
        - Autres: 'Societe/PreferencesSociete/2-5/OngletRacinesAutres.md'

