site_name: Aide en ligne

theme:
  name: material
  features : 
  - search
  - search.highlight
  highlightjs: True
  prev_next_buttons_location: top
  titles_only: True
  sticky_navigation: False

plugins:
  - search
  - offline
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - admonition

nav:
  - Bienvenue: 'index.md'
  - Conditions de licence des progiciels GESTIMUM et d'utilisation des services associés au 15/11/2019: 'CLS.md'
  - Notes de Version:
    - Bienvenue: 'NotesVersion/Racine/Bienvenue.md'
    - Mise en Garde: 'NotesVersion/Racine/MiseGarde.md'
    - Dénomination des versions: 'NotesVersion/Racine/DenominationVersion.md'
    - Développement sur mesure: 'NotesVersion/Racine/PFD.md'
    - Préconisations d'utilisation et d'installation: 'NotesVersion/Racine/PreconisationsUtilisationInstallation8.md'
  - Société:
    - Menu Société: 'Societe/Menu/Menu_SOCIETE.md'
    - Nouvelle société: 
      - Créer une nouvelle société: 
        - 'Societe/Nouvelle/1/CreerNouvelleSociete.md'
        - Nouvelle société: 'Societe/Nouvelle/1/NouvelleSociete.md'
        - Base de données: 'Societe/Nouvelle/1/BaseDonnees.md'
        - Raison sociale et adresse: 'Societe/Nouvelle/1/RaisonSocialeAdresse.md'
        - Exercices comptables: 'Societe/Nouvelle/1/ExercicesComptables.md'
        - Tableau des périodes d'exercices comptables: 'Societe/Nouvelle/1/TableauPeriodes.md'
        - Données par défaut: 'Societe/Nouvelle/1/DonneesDefaut.md'
      - Dupliquer une société: 'Societe/Nouvelle/2/DupliquerBaseDonnees.md'
      - Paramétrages après la création d'une société: 'Societe/Nouvelle/3/ParametragesApresCreationSociete.md'
    - Ouvrir une société:
      - Ouverture de société: 'Societe/Ouvrir/1/OuvertureSociete.md'
      - Assistant de création d'unmk  e connexion à une société existante:
        - Assistant de connexion: 
          - 'Societe/Ouvrir/2/AssistantConnexion.md'
          - Base de données: 'Societe/Ouvrir/2/BaseDonnees.md'
          - Utilisateur et options: 'Societe/Ouvrir/2/UtilisateurOptions.md'
    - Fermer la société: 'Societe/Fermer/FermerSociete.md'
    - Paramétrage:
      - Préférences de société:
        - 'Societe/PreferencesSociete/1/PreferencesSociete.md'
        - Coordonnées: 'Societe/PreferencesSociete/2-1/OngletCoordonnees.md'
        - Logo: 'Societe/PreferencesSociete/2-1/OngletLogo.md'
        - Identité: 'Societe/PreferencesSociete/2-2/OngletIdentite.md'
        - Exercices: 'Societe/PreferencesSociete/2-3/OngletExercices.md'
        - Comptabilité: 'Societe/PreferencesSociete/2-4/OngletComptabilite.md'
        - Transfert comptable: 'Societe/PreferencesSociete/2-4/OngletTransfertComptable.md'
        - Racines: 
          - 'Societe/PreferencesSociete/2-5/OngletRacines.md'
          - Immobilisations: 'Societe/PreferencesSociete/2-5/OngletRacinesImmoibilisations.md'
          - Stocks: 'Societe/PreferencesSociete/2-5/OngletRacinesStocks.md'
          - Tiers: 'Societe/PreferencesSociete/2-5/OngletRacinesTiers.md'
          - Taxes: 'Societe/PreferencesSociete/2-5/OngletRacinesTaxes.md'
          - Finances: 'Societe/PreferencesSociete/2-5/OngletRacinesFinances.md'
          - Charges et Produits: 'Societe/PreferencesSociete/2-5/OngletRacinesChargesProduits.md'
          - Autres: 'Societe/PreferencesSociete/2-5/OngletRacinesAutres.md'
        - Comptes: 'Societe/PreferencesSociete/2-6/OngletComptes.md'
        - Encaissements: 'Societe/PreferencesSociete/2-7/OngletEncaissements.md'
        - Compteurs: 
          - 'Societe/PreferencesSociete/2-8/OngletCompteurs.md'
          - Pièces de vente: 'Societe/PreferencesSociete/2-8/OngletCompteursVentes.md'
          - Pièces d'achat: 'Societe/PreferencesSociete/2-8/OngletCompteursAchats.md'
          - Pièces de stock: 'Societe/PreferencesSociete/2-8/OngletCompteursStocks.md'
          - Pièces de trésorerie: 'Societe/PreferencesSociete/2-8/OngletCompteursTresorerie.md'
          - Numéros internes: 'Societe/PreferencesSociete/2-8/OngletCompteursNumeriques.md'
        - Styles: 'Societe/PreferencesSociete/2-9/OngletStyles.md'
        - Avancé: 'Societe/PreferencesSociete/2-9/OngletAvance.md'
        - Impression des préférences de la société: 'Societe/PreferencesSociete/3/Impression.md'
        - Lettrage automatique lors du transfert comptable: 'Societe/PreferencesSociete/Trier/LettrageAutomatiqueTransfertComptable.md'
        - Mode Fiche: 'Societe/PreferencesSociete/Trier/ModeFiche.md'
      - Préférences de gestion :
        - 'Societe/PreferencesGestion/1/PreferencesGestion.md'
        - Articles: 
          - Articles: 'Societe/PreferencesGestion/2-1/OngletArticles.md'
          - Critères personnalisés: 'Societe/PreferencesGestion/2-1/OngletCriteresPersonnalises.md'
          - Taxes parafiscales: 'Societe/PreferencesGestion/2-1/OngletTaxesParafiscales.md'
        - Stocks:
          - 'Societe/PreferencesGestion/2-2/OngletStocks.md'
          - Numéros de lots: 'Societe/PreferencesGestion/2-2/OngletNumerosLots.md'
          - Numéros de séries:  'Societe/PreferencesGestion/2-2/OngletNumerosSeries.md'
        - Tiers:
          - 'Societe/PreferencesGestion/2-3/OngletTiers.md'
          - Critères personnalisés: 'Societe/PreferencesGestion/2-3/OngletCriteresPersonnalises.md'
        - Ventes, achats, stocks:
          - 'Societe/PreferencesGestion/2-4/OngletVentesAchatsStocks.md'
          - Ventes: 'Societe/PreferencesGestion/2-4/OngletVentesAchatsVentes1.md'
          - Achats:  'Societe/PreferencesGestion/2-4/OngletVentesAchatsAchats.md'
          - Noms des documents:
            - 'Societe/PreferencesGestion/2-4/Noms/OngletNomsDocuments.md'
            - Ventes: 'Societe/PreferencesGestion/2-4/Noms/OngletNomsVentes.md'
            - Achats: 'Societe/PreferencesGestion/2-4/Noms/OngletNomsAchats.md'
            - Stocks: 'Societe/PreferencesGestion/2-4/Noms/OngletNomsStocks.md'
          - Modèles par défaut:
            - 'Societe/PreferencesGestion/2-4/Modeles/OngletVentesAchatsStocksModelesDefaut.md'
            - Ventes: 'Societe/PreferencesGestion/2-4/Modeles/OngletModelesVentes.md'
            - Achats: 'Societe/PreferencesGestion/2-4/Modeles/OngletModelesAchats.md'
            - Stocks: 'Societe/PreferencesGestion/2-4/Modeles/OngletModelesStocks.md'
          - Mentions obligatoires: 'Societe/PreferencesGestion/2-4/OngletMentionsObligatoires.md'
        - Affaires:
          - 'Societe/PreferencesGestion/2-5/OngletAffaires.md'
          - Ajouter les jours fériés: 'Societe/PreferencesGestion/2-5/AjouterJoursFeries.md'
        - Salariés: 
          - Critères personnalisés: 'Societe/PreferencesGestion/2-6/CriteresPersonnalises.md'
        - Impression des préférences de gestion: 'Societe/PreferencesGestion/3/Impression.md'
        - Messages d'avertissement ou bloquant: 'Societe/PreferencesGestion/Trier/MessagesAvertissementBloquant.md'
        - Date de livraison: 'Societe/PreferencesGestion/Trier/DateLivraison.md'
      - Préférences de comptabilité:
        - 'Societe/PreferencesCompta/1/PreferencesComptabilite.md'
        - Comptabilité: 'Societe/PreferencesCompta/2-1/OngletComptabilite.md'
        - Déclarations de TVA: 'Societe/PreferencesCompta/2-2/OngletDeclarationsTVA.md'
        - Fiscalité - FEC: 'Societe/PreferencesCompta/2-3/OngletFiscalite.md'
        - Trésor Public: 'Societe/PreferencesCompta/2-4/OngletTresorPublic.md'
        - Rapprochements bancaires: 'Societe/PreferencesCompta/2-5/OngletRapprochementsBancaires.md'
        - Immobilisations: 'Societe/PreferencesCompta/2-6/OngletImmobilisations.md'
        - Impression des préférences de comptabilité: 'Societe/PreferencesCompta/3/ImpressionPreferencesComptabilite.md'
      - Préférences utilisateur:
        - 'Societe/PreferencesUtilisateur/1/PreferencesUtilisateur.md'
        - Dossiers: 'Societe/PreferencesUtilisateur/2-1/OngletDossiers.md'
        - Imports d'achats, ventes et stocks: 'Societe/PreferencesUtilisateur/2-2/OngletImportAchatsVentesStocks.md'
        - Exports d'achats, ventes et stocks: 'Societe/PreferencesUtilisateur/2-3/OngletExportsAchatsVentesStocks.md'
        - Options: 'Societe/PreferencesUtilisateur/2-4/OngletOptions.md'
        - Documentation: 'Societe/PreferencesUtilisateur/2-5/OngletDocumentation.md'
        - Fichiers de configuartion: 'Societe/PreferencesUtilisateur/2-6/OngletFichiersConfiguration.md'
        - base de données: 'Societe/PreferencesUtilisateur/2-7/OngletBaseDonnees.md'
      - Tables de références:
        - Présentation: 'Societe/TablesReferences/1/Presentation.md'
        - Liste des tables de référence: 
          - Liste des tables de référence: 'Societe/TablesReferences/2/Liste.md'
          - Tables générales: 'Societe/TablesReferences/2/TablesReferenceGenerales.md'
          - Tables pour les affaires: 'Societe/TablesReferences/2/Affaires.md'
          - Tables pour les articles: 'Societe/TablesReferences/2/Articles.md'
          - Tables pour la comptabilité: 'Societe/TablesReferences/2/Comptabilite.md'
          - Tables pour les contacts: 'Societe/TablesReferences/2/Contacts.md'
          - Tables pour les documents d'achat, vente et stock: 'Societe/TablesReferences/2/DocumentsAchatVenteStock.md'
          - Tables pour les encaissements et décaissements: 'Societe/TablesReferences/2/TablesReferenceEncaissementsDecaissements.md'
          - Tables pour la prospection: 'Societe/TablesReferences/2/Prospection.md'
          - Tables pour les salariés: 'Societe/TablesReferences/2/TablesSalaries.md'
          - Tables pour le stock: 'Societe/TablesReferences/2/TablesStock.md'
          - Tables pour les tiers: 'Societe/TablesReferences/2/TablesTiers.md'
        - Saisie de valeurs dans les tables de référence: 'Societe/TablesReferences/3/SaisieValeurs.md'
        - Impression des tables de référence: 'Societe/TablesReferences/4/Impression.md'
      - Champs personnalisables:
        - Introduction: 'Societe/ChampsPersonnalises/0/Introduction.md'
        - Paramétrage: 
          - Création d'un champ personnalisé: 'Societe/ChampsPersonnalises/1/CreationChampPersonnalise.md'
          - Résultat dans les fenêtres concernées: 'Societe/ChampsPersonnalises/ResultatFenêrtesConcernees.md'
          - Valeurs possibles d'une liste déroulante: 'Societe/ChampsPersonnalises/2/ValeursPossiblesListeDeroulante.md'
          - Liste déroulante avec les valeurs d'une table: 'Societe/ChampsPersonnalises/3/ListeDeroulanteTableLiee.md'
          - Champs personnalisés calculés: 'Societe/ChampsPersonnalises/4/ChampsPersonnalisesCalcules.md'
          - Compteurs: 'Societe/ChampsPersonnalises/4/Compteurs.md'
          - Champs personnalisés obligatoires: 'Societe/ChampsPersonnalises/5/ChampsPersonnalisesObligatoires.md'
          - Conditions de visibilité: 'Societe/ChampsPersonnalises/6/ConditionsVisibilite.md'
        - Champs personnalisés dans les personnalisations de listes: 'Societe/ChampsPersonnalises/7/PersonnalisationsListes.md'
        - Recopie automatique de champs personnalisés entre tables: 'Societe/ChampsPersonnalises/8/RecopieAutomatiqueEntreTables.md'
      - Débrider mon ERP : 'Societe/Debridage/DebriderMonERP.md'
    - Services:
      - Liste des services: 'Societe/Services/1/Liste.md'
      - Service:
        - 'Societe/Services/2/Service.md'
        - Général: 'Societe/Services/2/OngletGeneral.md'
        - Divisions: 'Societe/Services/2/OngletDivisions.md'
      - Impression des services: 'Societe/Services/3/Impression.md'
    - Salariés:
      - Introduction: 'Societe/Salaries/1/Introduction.md'
      - Liste des salariés: 'Societe/Salaries/2/Liste.md'
      - Salariés:
        - Salariés: 'Societe/Salaries/3/Salarie.md'
        - Général: 'Societe/Salaries/3/OngletGeneral.md'
        - Affectations: 'Societe/Salaries/3/OngletAffectations.md'
        - Dépôts: 'Societe/Salaries/3/OngletDepots.md'
        - Affaires: 'Societe/Salaries/3/OngletAffaires.md'
        - Absences: 'Societe/Salaries/3/OngletAbsences.md'
        - Actions:  'Societe/Salaries/3/OngletActions.md'
        - Personnalisé: 'Societe/Salaries/3/OngletPersonnalise.md'
      #- Import:
      #  - Import de salariés:
      #  - Type de fichier:
      #  - Structure du fichier de salariésorerie:
      #  - Exemple:
      #    - Exemple de fichier de salariés:
      #    - Exemple d'import de salariés:
      - Impression des salariés: 'Societe/Salaries/4/Impression.md'
    - Utilisateurs:
      - Introduction: 'Societe/Utilisateurs/1/Introduction.md'
      - Paramétrage des utilisateurs: 'Societe/Utilisateurs/1/ParametrageUtilisateurs.md'
      - Groupes:
        - Liste des groupes d'utilisateurs: 'Societe/Utilisateurs/2/ListeGroupes.md'
        - Groupe d'utilisateurs: 'Societe/Utilisateurs/2/Groupe.md'
      - Utilisateurs:
        - Liste des utilisateurs: 'Societe/Utilisateurs/3/ListeUtilisateurs.md'
        - Utilisateur: 'Societe/Utilisateurs/3/Utilisateur.md'
      - Autorisations: 
        - Autorisations des utilisateurs et des groupes: 'Societe/Utilisateurs/4/Autorisations.md'
        - Droits d'utilisation: 'Societe/Utilisateurs/5/DroitsUtilisation.md'
      - Mot de passe: 
        - Confirmation du mot de passe: 'Societe/Utilisateurs/6/ConfirmationMotPasse.md'
        - Changer le mot de passe: 'Societe/Utilisateurs/6/ChangerMotPasse.md'
      #- Import: 
      #  - Import d'utilisateurs: 
      #  - Type de fichier: 
      #  - Structure du fichier d'utilisateurs:
      #  - Exemple:
      #    - Exemple de fichier d'utilisateurs:
      #    - Exemple d'import d'utilisateurs:
    - Commerciaux:
      - Introduction: 'Societe/Commerciaux/1/Introduction1.md'
      - Commerciaux:
        - Introduction: 'Societe/Commerciaux/2/Introduction2.md'
        - Liste des commerciaux: 'Societe/Commerciaux/2/ListeCommerciaux.md'
        - Commercial: 
          - Commercial: 'Societe/Commerciaux/2/Commercial.md'
          - Coordonnées: 'Societe/Commerciaux/2/OngletCoordonnees.md'
          - Autre: 'Societe/Commerciaux/2/OngletAutre.md'
        #- Import: 
        #  - Import de commerciaux: 
        #  - Type de fichier: 
        #  - Structure du fichier de commerciaux: 
        #  - Exemple: 
        #    - Exemple de fichier de commerciaux: 
        #    - Exemple d'import de commerciaux: 
        - Impression des commerciaux: 'Societe/Commerciaux/2/Impression/ImpressionCommerciaux.md'
      - Filtres: 
        - Filtres en fonction du commercial connecté: 'Societe/Commerciaux/4/FiltresCommercialConnecte.md'
      - Barèmes de commissionnements: 
        - Introduction: 'Societe/Commerciaux/3/Introduction3.md'
        - Liste des barèmes: 'Societe/Commerciaux/3/ListeBaremes.md'
        - Barème: 
          - Barème: 'Societe/Commerciaux/3/Bareme.md'
          - Objectifs: 'Societe/Commerciaux/3/BaremeObjectifs.md'
          - Sélection: 'Societe/Commerciaux/3/BaremeSelection.md'
        - Impression des barèmes commerciaux: 'Societe/Commerciaux/3/Impression/ImpressionBaremesCommerciaux.md'
    - Devises: 
      - Liste des devises: 'Societe/Devises/1/ListeDevises.md'
      - Devise: 'Societe/Devises/2/Devise.md'
      - Cotation "Au certain": 'Societe/Devises/2/CotationCertain.md'
      - Cotation "A l'incertain": 'Societe/Devises/2/CotationIncertain.md'
      - Devise locale: 'Societe/Devises/3/DeviseLocale.md'
      - Devise société: 'Societe/Devises/3/DeviseSociete.md'
      #- Import: 
      #  - Import de devises: 
      #  - Type de fichier: 
      #  - Structure du fichier de devises: 
      #  - Exemple : 
      #    - Exemple de fichier de devises: 
      #    - Exemple d'import de devises: 
      - Impression des devises: 'Societe/Devises/5/ImpressionDevises.md'
      - Outils: 
        - Outils d'actualisation du certain et de l'incertain des devises: 'Societe/Devises/6/OutilActualisationCertainIncertain.md'
        - Actualisation en ligne des cours des devises: 'Societe/Devises/6/ActualisationLigneCoursDevises.md'
        - Actualisation manuelle des cours des devises: 'Societe/Devises/6/ActualisationManuelleCoursDevises.md'
      - Devises de A à Z: 'Societe/Devises/7/DevisesAZ.md'
      - Les devises: 'Societe/Devises/Trier/LesDevises.md'
      - Devise d'un journal ou d'un compte: 'Societe/Devises/Trier/DeviseJournalCompte.md'
      - Devise d'un tiers: 'Societe/Devises/Trier/DeviseTiers.md'
      - Prix en devise: 'Societe/Devises/Trier/PrixDevise.md'
      - Conversion de devise: 'Societe/Devises/Trier/ConversionDevise.md'
    - Mode de règlements:
      - Introduction: 'Societe/ModesReglement/1/Introduction.md'
      - Liste des modes de règlements: 'Societe/ModesReglement/2/ListeModesReglements.md'
      - Mode de règlement: 'Societe/ModesReglement/3/ModeReglement.md'
      - Règles de codification: 'Societe/ModesReglement/4/ReglesCodification.md'
      #- Import: 
      #  - Import de modes de règlements: 
      #  - Type de fichier :
      #  - Structure du fichier de modes de règlements :
      #  - Exemple: 
      #    - Exemple de fichier de modes de règlements: 
      #    - Exemple d'import de modes de règlements: 
      - Impression des modes de règlements: 'Societe/ModesReglement/5/ImpressionModesReglements.md'
    - Frais: 
      - Liste des frais: 'Societe/Frais/1/ListeFrais.md'
      - Frais : 
        - 'Societe/Frais/2/Frais.md'
        - Général: 'Societe/Frais/2/OngletGeneral.md'
        - Comptabilité: 'Societe/Frais/2/OngletComptabilite.md'
      - Impression des frais: 'Societe/Frais/3/ImpressionFrais.md'
      - Frais complémentaires: 'Societe/Frais/Trier/Frais.md'
    - Transporteurs: 
      - Liste des transporteurs: 'Societe/Transporteurs/1/Transporteurs.md'
      - Transporteur: 'Societe/Transporteurs/2/Transporteur.md'
      - Impression des transporteurs: 'Societe/Transporteurs/3/Impression.md'